name: Build and Push sprite75/headshotbox

on:
  push:
    branches: [ main ]
    paths: [ "headshotbox/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Check buildx
      run: docker buildx ls
    - name: Build
      run: >
        docker build .
          --file ./headshotbox/Dockerfile
          -t ${{secrets.DOCKER_USER}}/headshotbox:latest
          -t ${{secrets.DOCKER_USER}}/headshotbox:$(cat ./headshotbox/version) 
    - name: Push
      run: docker push -a ${{secrets.DOCKER_USER}}/headshotbox
    - name: Update description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: ${{secrets.DOCKER_USER}}/headshotbox
        short-description: Headshotbox in docker!
        readme-filepath: headshotbox/README.md
