name: Build and Push sprite75/namecheap_ddns

on:
  push:
    branches: [ main ]
    paths: [ ".github/workflows/namecheap_ddns.yml", "namecheap_ddns/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build
      run: docker build . --file ./namecheap_ddns/Dockerfile -t ${{secrets.DOCKER_USER}}/namecheap_ddns:latest -t ${{secrets.DOCKER_USER}}/namecheap_ddns:$(cat ./namecheap_ddns/version) 
    - name: Push
      run: docker push -a ${{secrets.DOCKER_USER}}/namecheap_ddns
    - name: Update description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: ${{secrets.DOCKER_USER}}/namecheap_ddns
        short-description: Dynamic DNS in docker!
        readme-filepath: namecheap_ddns/README.md
