name: Build and Push sprite75/namecheap_ddns

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build
      run: docker build ./namecheap_ddns -t ${{secrets.DOCKER_USER}}/namecheap_ddns
    - name: Push
      run: docker push ${{secrets.DOCKER_USER}}/namecheap_ddns
