name: Build and Push sprite75/scout_realtime

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build
      run: docker build . --file ./scout_realtime/Dockerfile -t scout_realtime:$(date +%s)
    - name: Push
      run: docker push ${{secrets.DOCKER_USER}}/scout_realtime
