name: Build and Push sprite75/scout_realtime

on:
  push:
    branches: [ main ]
    paths:
      - "scout_realtime/**"
      - "arm32v6/scout_realtime/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Check buildx
      run: docker buildx ls
    - name: Build
      run: docker build . --file ./scout_realtime/Dockerfile -t ${{secrets.DOCKER_USER}}/scout_realtime
    - name: Push
      run: docker push ${{secrets.DOCKER_USER}}/scout_realtime
