name: Build and Push sprite75/scout_realtime

on:
  push:
    branches: [ main ]
    paths: [ ".github/workflows/scout_realtime.yml", "scout_realtime/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Check buildx
      run: docker buildx ls
    - name: Build
      run: docker build . --file ./scout_realtime/Dockerfile -t ${{secrets.DOCKER_USER}}/scout_realtime:latest -t ${{secrets.DOCKER_USER}}/scout_realtime:$(cat ./scout_realtime/version) 
    - name: Push
      run: docker push -a ${{secrets.DOCKER_USER}}/scout_realtime
    - name: Update description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: ${{secrets.DOCKER_USER}}/scout_realtime
        short-description: Scout Realtime in docker!
        readme-filepath: scout_realtime/README.md
