name: Build and Push sprite75/tf2

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Check buildx
      run: docker buildx ls
    - name: Build
      run: docker build . --file ./dedicated-servers/tf2/Dockerfile -t ${{secrets.DOCKER_USER}}/tf2
    - name: Push
      run: docker push ${{secrets.DOCKER_USER}}/tf2
